services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-psmm}
      POSTGRES_USER: ${POSTGRES_USER:-psmm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-psmm}
    volumes:
      - psmm_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - psmm_redis_data:/data

volumes:
  psmm_postgres_data:
  psmm_redis_data:
